### ISSUE TITLE
Aternos Crash

### ISSUE THREAD

**Issue by Cobalt22** [NillerMedDild/Enigmatica4#411]
**Modpack version**
0.5.4

**Issue**
Trying to host a server with this modpack on Aternos but it crashes every time i try and activate the server

**Logs**
https://mclo.gs/rWyoY4a

**Comment by NielsPilgaard** [comment]
Please supply the crash report,

**Comment by Cobalt22** [comment]
https://mclo.gs/rWyoY4a

<blockquote><div><strong><a href="https://mclo.gs/rWyoY4a">Attention Required! | Cloudflare</a></strong></div></blockquote>

**Comment by Justin-J-Morgan** [comment]
I am having the same issue. my crash report is here: https://mclo.gs/w2Gc2Oq might be the same issue, might not be.

The client side was also having an issue on my laptop. I think it isn't installing 1.14.4 when it installed the modpack, log pasted below. I tried to scrub the PII...

[22:07:17] [main/INFO]: ModLauncher running: args [--username, ~~ --version, forge-28.2.4, --gameDir, C:~~Twitch\Minecraft\Instances\Enigmatica 4, --assetsDir, C:~~Twitch\Minecraft\Install\assets, --assetIndex, 1.14, --uuid, 3c63d0da7f054e68a0e05aad95fd1769, --accessToken, ????????, --userType, mojang, --versionType, release, --width, 1024, --height, 768, --launchTarget, fmlclient, --fml.forgeVersion, 28.2.4, --fml.mcVersion, 1.14.4, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20190829.143755]
[22:07:17] [main/INFO]: ModLauncher 4.1.0+62+5bfa59b starting: java version 1.8.0_51 by Oracle Corporation
[22:07:18] [main/INFO]: Added Lets Encrypt root certificates as additional trust
**[22:07:18] [main/FATAL]: Failed to find Minecraft resource version 1.14.4-20190829.143755 at** **C:~~Twitch\Minecraft\Install\libraries\net\minecraftforge\forge\1.14.4-28.2.4\forge-1.14.4-28.2.4-client.jar
[22:07:18] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.RuntimeException: Missing minecraft resource!**
[22:07:18] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.loading.FMLCommonLaunchHandler.lambda$validatePaths$4(FMLCommonLaunchHandler.java:124)
[22:07:18] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.loading.FMLCommonLaunchHandler$$Lambda$136/40075281.accept(Unknown Source)
[22:07:18] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
[22:07:18] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
[22:07:18] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.loading.FMLCommonLaunchHandler.validatePaths(FMLCommonLaunchHandler.java:121)
[22:07:18] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.loading.FMLLoader.setupLaunchHandler(FMLLoader.java:195)
[22:07:18] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.loading.FMLServiceProvider.initialize(FMLServiceProvider.java:92)
[22:07:18] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServiceDecorator.onInitialize(TransformationServiceDecorator.java:68)
[22:07:18] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServicesHandler.lambda$initialiseTransformationServices$7(TransformationServicesHandler.java:107)
[22:07:18] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServicesHandler$$Lambda$84/1108924067.accept(Unknown Source)
[22:07:18] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.HashMap$Values.forEach(HashMap.java:972)
[22:07:18] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServicesHandler.initialiseTransformationServices(TransformationServicesHandler.java:107)
[22:07:18] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:59)
[22:07:18] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:75)
[22:07:18] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)


<blockquote><div><strong><a href="https://mclo.gs/w2Gc2Oq">Attention Required! | Cloudflare</a></strong></div></blockquote>

**Comment by NielsPilgaard** [comment]
@Justin-J-Morgan That's not a crash report, and there's no crash in there as far as I can tell, but the formatting on that log is horrible so it's hard to tell :P

The text you pasted in is a Twitch issue, it tends to suck at downloading Minecraft for 1.14+, see this issue: #281 

Also, please use a pasting website such as https://pastebin.com or https://gist.github.com, so I can read what you send me.

<blockquote><img src="https://pastebin.com/i/facebook.png" width="48" align="right"><div>Pastebin</div><div><strong><a href="https://pastebin.com/">Pastebin.com - #1 paste tool since 2002!</a></strong></div><div>Pastebin.com is the number one paste tool since 2002. Pastebin is a website where you can store text online for a set period of time.</div></blockquote>
<blockquote><img src="https://github.com/opengraph.png" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> Gist</div><div><strong><a href="https://gist.github.com/">Discover gists</a></strong></div><div>GitHub Gist: instantly share code, notes, and snippets.</div></blockquote>

**Comment by NielsPilgaard** [comment]
@Cobalt22 That's still not a crash report, that is another debug.log.

**Comment by Justin-J-Morgan** [comment]
I'm not sure where to find the crash report then.  But loading from my desktop, it all loads up just fine. It seems to be an issue local to my laptop.

**Comment by Justin-J-Morgan** [comment]
Just not sure why a 3rd party server would have an issue.

**Comment by NielsPilgaard** [comment]
Crash reports are stored in a folder called crash-reports.
